name: convertx
description: Encoders and decoders for converting between different data representations, using extensions.
version: 0.0.1
homepage: https://github.com/parsodyl/convertx
author: Daniele Paradiso (mac) <parsodyl@gmail.com>

environment:
  sdk: '>=2.6.0-dev <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
