name: convertx
description: Static extension methods for converting between different data representations.
version: 0.2.2
homepage: https://github.com/parsodyl/convertx

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.4
